# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: monospace

  # Point size
  size: 13
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

# Cursor style
cursor:
  style: Block

# Window position on startup
window:
   dimensions:
     columns: 85
     lines: 50

   padding:
     x: 15
     y: 10
